### ISSUE TITLE
Would like to contact you by email?

### ISSUE THREAD

**Issue by mgoeller** [Anton-K-dev/dali2_application_controller#1]
Hi, I would like to contact you via email, can you reach out to mg (at) atios.ch?

Thank you!

**Comment by Anton-K-dev** [comment]
Hi, are you interested by dali driver? Can you describe your attention?
Best regards, Anton.

вт, 30 апр. 2024 г., 23:24 mgoeller ***@***.***>:

**Comment by mgoeller** [comment]
Hi, exactly, looking for a developer for a DALI driver in C.

**Comment by Anton-K-dev** [comment]
I'm interested of cooperation, what's your goal regarding dali? I mean just
specific led/dimmer control by specific devices as application controller
on smart home or dali control gear/devices development?
Also I'll note, that I'm from Ukraine and I'm not able to relocate out of
border, only remote powered by delivery option.

ср, 1 мая 2024 г., 18:35 mgoeller ***@***.***>:

**Comment by mgoeller** [comment]
We want to implement control via DALI for:
- more device types, currently only brightness and dimming. Future: tuneable white, rgbw etc.
- support of DALI-2 push buttons
- addressing of DALI devices via webinterface
- etc.etc.

I am aware, remote is absolutely possible. Please contact me by email: mg (at) atios.ch

**Comment by Anton-K-dev** [comment]
I've contacted you via mg (at) atios.ch, please notify me as soon as you
reach the message.

пт, 3 мая 2024 г. в 17:12, mgoeller ***@***.***>:
